---
- name: Ensure jailed user exists.
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    append: true
    shell: "{{ item.shell | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    createhome: "{{ item.createhome | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    remove: yes
  register: user_task

- name: Ensure the key is added to the user
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key | default(omit) }}"
  # when:
  #   item.state is present

- name: Ensure jailed user has a homedir inside the jail (if configured).
  file:
    path: "{{ ssh_chroot_jail_path }}{{ item.home }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  when: item.home is defined

- name: Ensure account skeleton files are copied into jailed user's home.
  command: "cp -r -n /etc/skel/. {{ ssh_chroot_jail_path }}{{ item.home }}"
  args:
    warn: false
  become: true
  #become_user: "{{ item.name }}"
  failed_when: false
  when:
    - item.home is defined
    - user_task.changed